version: '3'

services:
    server_test:
        image: server_test
        ports:
            - "8002:5000"
        volumes:
            - ./:/code
            - "/root/backend/folio_backend/app/Public/Job/File:/code/Public/Job/File"
        restart: always
        networks:
            - code-network-dev
networks:
    code-network-dev:
        driver: bridge
